### ISSUE TITLE
Setup instructions unclear

### ISSUE THREAD

**Issue by n2liquid** [luizalabs/teresa#183]
* teresa-api version: a21b7d646174814108e491212b8702108c40f4f1 (0.3.1?)
* K8s version: 1.5.2

I've followed all steps outlined on the teresa-api readme file, however the teresa-api pod fails with the following error message:

    time="2017-04-27T00:43:30Z" level=fatal msg="the server could not find the requested resource (get secrets teresa-keys)"

Even though `teresa-keys` exist:

    $ kubectl get secrets teresa-keys -n teresa
    NAME          TYPE      DATA      AGE
    teresa-keys   Opaque    2         2d

This is the deployment file:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teresa
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: teresa
    spec:
      containers:
      - name: teresa
        image: cmgvieira/teresa:latest
        ports:
        - containerPort: 8080
        env:
          - name: TERESAK8S_HOST
            value: [MY K8S HOST]
          - name: TERESAK8S_USERNAME
            value: [MY K8S USERNAME COPIED FROM ~/.kube/config]
          - name: TERESAK8S_PASSWORD
            value: [MY K8S PASSWORD COPIED FROM ~/.kube/config]
          - name: TERESAK8S_INSECURE
            value: "true"
          - name: TERESAFILESTORAGE_TYPE
            value: s3
          - name: TERESAFILESTORAGE_AWS_KEY
            value: [MY S3 AWS KEY]
          - name: TERESAFILESTORAGE_AWS_SECRET
            value: MY S3 AWS SECRET]
          - name: TERESAFILESTORAGE_AWS_REGION
            value: us-east-1
          - name: TERESAFILESTORAGE_AWS_BUCKET
            value: [MY BUCKET NAME]
          - name: TERESADEPLOY_REVISION_HISTORY_LIMIT
            value: "5"
          - name: TERESADEPLOY_START_TIMEOUT
            value: 10m
          - name: TERESADEPLOY_FINISH_TIMEOUT
            value: 30m
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```

Unless I'm missing something from the readme, I think it should be updated with clearer instructions.
