### ISSUE TITLE
Ingress shouldn't be created for apps with empty Vhost

### ISSUE THREAD

**Issue by vinicyusmacedo** [luizalabs/teresa#627]
If you toggle Ingress on a Teresa server deployment after some apps have been created without it, ingresses might be created without any host.

To replicate this bug:

- Change the `teresa.io/app` annotation – leave an empty string on virtualHost and false on reserveStaticIp
- Make sure ingress is enabled on Teresa
- Make a web deployment
- Ingress will be created, without any Host

```
  spec:
    rules:
    - http:
        paths:
        - backend:
            serviceName: myapp
            servicePort: 80
          path: /
```

Alternatively, the path can be a catch all `/*`, this way it'll work the same way as specify no rules.
